name: Deploy via SSH

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to SSH Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Increase the maximum number of user processes
        run: ulimit -u 1024

      - name: Run deployment script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          request_pty: true
          script_stop: true
          script: |
            become capx-test git -C '$HOME/www/js' fetch origin
            become capx-test git -C '$HOME/www/js' reset --hard origin/dev
            become capx-test git -C '$HOME/www/js' pull origin dev
            become capx-test webservice --mem 2G --cpu 2 node18 shell -- yarn --cwd '$HOME/www/js' install
            become capx-test webservice --mem 2G --cpu 2 node18 shell -- yarn --cwd '$HOME/www/js' build
            become capx-test webservice restart
