name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to SSH Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          request_pty: true
          script_stop: true
          script: |
            become capx git -C '$HOME/www/js' pull origin main
            become capx webservice --mem 2G --cpu 1 node18 shell -- yarn --cwd '$HOME/www/js' install
            become capx webservice --mem 2G --cpu 1 node18 shell -- yarn --cwd '$HOME/www/js' build
